spring.application.name=career-companion
spring.datasource.url=jdbc:mysql://localhost:3306/career_companion
spring.datasource.username=root
spring.datasource.password=Archana114
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

